version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - BOT_TOKEN=
      - PREFIX=,
      - DB_PORT=5432
      - DB_NAME=exodia
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_LOGGIN=false
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meu-banco
      - POSTGRES_USER=meu-usuario
      - POSTGRES_PASSWORD=minha-senha
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: '3'
volumes:
  postgres-data:
