version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PREFIX=${PREFIX}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_LOGGIN=${DB_LOGGIN}
      - DAILY_MAX_REQUESTS=${DAILY_MAX_REQUESTS}
      - NEWSAPI_API_KEY=${NEWSAPI_API_KEY}
    depends_on:
      - ffmpeg

  ffmpeg:
    container_name: b2c-ffmpeg
    image: jrottenberg/ffmpeg
    #tty: true
    networks:
      - b2c
    ports:
      - '29002:29000'
    tty: true
    entrypoint: 'bash'
    
volumes:
  postgres-data:
